name: Test (PyPI)

on:
  schedule:
    - cron: "0 18 * * 1,3,5"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
        tensorflow: ["tensorflow", "tensorflow<2"]
        exclude:
          - python-version: 3.8
            tensorflow: "tensorflow<2"

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip wheel setuptools
      - run: pip install pytest
      - run: pip install "${{ matrix.tensorflow }}"
      - uses: actions/checkout@v2

      - name: Install package from source (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew config
          brew install gcc@9
          pip install --no-binary stardist stardist
        env:
          CC: /usr/local/bin/gcc-9
          CXX: /usr/local/bin/g++-9

      - name: Install package from source (Linux and Windows)
        if: startsWith(matrix.os, 'macos') == false
        run: pip install --no-binary stardist stardist

      # - name: Install package from wheel
      #   run: |
      #     pip uninstall -y stardist
      #     pip install --no-cache-dir --only-binary stardist "stardist>0"

      - run: pytest -v --durations=50 -m "not gpu"